print(
    "currences: \n USD, AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, \n BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL, BSD, \n BTN, BWP, BYR, BZD, CAD, CDF, CHF, CKD, CLP, CNY, COP, \n CRC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP, ERN, ETB, \n EUR, FJD, FKP, FOK, GBP, GEL, GGP, GHS, GIP, GMD, GNF, \n GTQ, GYD, HDK, HNL, HRK, HTG, HUF, HDR, ILS, IMP, INR, \n IQD, IRR, ISK, JEP, JMD, JPY, KES, KGS, KHR, KID, KMF, \n KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL, LYD, \n MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRO, MUR, MVR, MWK, \n MXN, MYR, MZN, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, \n PEN, PGK, PHP, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR, \n SBD, SRC, SDG, SEK, SGD, SHP, SLL, SOS, SRD, SSP, STD, \n SYP, SZL, THB, TJS, TMT, TND, TOP, TRY, TTD, TVD, TWD, \n TZS, UAH, UGX, UYU, UZS, VEF, VND, VUV, WST, XAF, XCD, \n XOF, XPF, YER, ZAR, ZMW, ZWL"
)


